name: Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]   # Add this line to trigger on version tags
  workflow_dispatch:

env:
  archive_name: pl2303-$(date +%Y%m%d%H%M%S)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: walkero/amigagccondocker:os4-gcc11
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          CROSS_COMPILE=ppc-amigaos- make

      - name: Compress binaries with Lha (timestamped)
        run: |
          TS=$(date +%Y%m%d%H%M%S)
          ARCHIVE="pl2303_${TS}.lha"
          lha a "$ARCHIVE" pl2303.usbfd pl2303.fdclass
          echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV

      - name: Upload LHA release file in GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /opt/code/${{ env.ARCHIVE }}
          asset_name: ${{ env.ARCHIVE }}
          asset_content_type: application/x-lzh-compressed