name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  archive_name: pl2303-$(date +%Y%m%d%H%M%S)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: walkero/amigagccondocker:os4-gcc11
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          CROSS_COMPILE=ppc-amigaos- make

      - name: Upload binaries to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: pl2303
          path: |
            pl2303.usbfd
            pl2303.fdclass