name: Build



  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Docker
        run: |
          docker run -v ${{ github.workspace }}:/opt/code -w /opt/code walkero/amigagccondocker:os4-gcc11 /bin/bash -c "su amidev -c 'CROSS_COMPILE=ppc-amigaos- make'"

      - name: Install Lha
        run: |
          sudo apt-get update
          sudo apt-get install -y lha

      - name: Compress binaries with Lha (timestamped)
        run: |
          TS=$(date +%Y%m%d%H%M%S)
          ARCHIVE=pl2303_${TS}.lha
          lha a "$ARCHIVE" pl2303.usbfd pl2303.fdclass
          echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV

      - name: Upload package to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: pl2303
          path: ${{ env.ARCHIVE }}
